---
name: Test run

on:
    pull_request:
        branches: ["main", "develop"]

env:
    CARGO_TERM_COLOR: always

jobs:
    run-linux:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v3
            - name: run
              run: cargo run -- --name testrun

    run-windows:
        runs-on: windows-latest

        steps:
            - uses: actions/checkout@v3
            - name: run
              run: cargo run -- --name testrun

    run-macos:
        runs-on: macos-latest

        steps:
            - uses: actions/checkout@v3
            - name: run
              run: cargo run -- --name testrun
