---
name: Test run

on:
    pull_request:
        branches: ["main", "develop"]

env:
    CARGO_TERM_COLOR: always

jobs:
    run-linux:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v3
            - name: Build
              run: ./scripts/linux/install.sh

            - name: run
              run: |
                  git config --global user.email "you@example.com"
                  git config --global user.name "Your Name"
                  cargo run -- --name testrun

    run-windows:
        runs-on: windows-latest

        steps:
            - uses: actions/checkout@v3
            - name: Build
              run: ./scripts/win/install.bat

            - name: run
              run: |
                  git config --global user.email "you@example.com"
                  git config --global user.name "Your Name"
                  cargo run -- --name testrun

    run-macos:
        runs-on: macos-latest

        steps:
            - uses: actions/checkout@v3
            - name: Build
              run: ./scripts/macos/install.sh

            - name: run
              run: cargo run -- --name testrun
