---
name: Create issues from TODOs

on:
    push:
        branches:
            - develop

permissions:
    issues: write
    repository-projects: read
    contents: read

jobs:
    todos:
        runs-on: ubuntu-latest
        permissions:
            issues: write
            repository-projects: read
            contents: read

        steps:
            - uses: actions/checkout@v3

            - name: Run Issue Bot
              uses: derjuulsn/todo-issue@main
              with:
                  excludePattern: "^(node_modules/)"
                  blobLines: 7
                  blobLinesBefore: 4
                  keywords: "FIXME,BUG,WONTFIX,TODO,WARN,HACK,PERF,OPTIM,NOTE"
                  reopenClosed: true
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
